const Data = [
    {
      id: "1",
      city: "Almaty",
      location: "Panfilov Street",
      category: "Room",
      price: 70000,
      img: "https://media.istockphoto.com/id/1289883686/fr/photo/appartement-spacieux-avec-mur-de-fen%C3%AAtre.jpg?s=612x612&w=0&k=20&c=k9Dg_10QHtyZQ4f__8pNPKgKb4DIwuTLdruYqDwoHc0=",
      desc: "Private room in LES available march 1st. Must like dogs and cats. No couples. Close to trains and laundry mat",
      amenities: ['Pets welcome', 'Private bath', 'Wifi included', 'Free parking'],
      duraction: '12 month',
      rooms: 2,
      gender: 'Female',
      verified: true,
    },
    {
      id: "2",
      city: "Astana",
      location: "Panfilov Street",
      category: "Appartement",
      price: 500000,
      img: "https://media.istockphoto.com/id/1289883686/fr/photo/appartement-spacieux-avec-mur-de-fen%C3%AAtre.jpg?s=612x612&w=0&k=20&c=k9Dg_10QHtyZQ4f__8pNPKgKb4DIwuTLdruYqDwoHc0=",
      desc: "Private room in LES available march 1st. Must like dogs and cats. No couples. Close to trains and laundry mat",
      amenities: ['Pets welcome', 'Elevator', 'Wifi included', 'Free parking'],
      duraction: 'Flexible',
      rooms: 1,
      gender: 'Male',
      verified: false,
    },
    {
      id: "3",
      city: "Almaty",
      location: "Panfilov Street",
      category: "Room",
      price: 100000,
      img: "https://media.istockphoto.com/id/1289883686/fr/photo/appartement-spacieux-avec-mur-de-fen%C3%AAtre.jpg?s=612x612&w=0&k=20&c=k9Dg_10QHtyZQ4f__8pNPKgKb4DIwuTLdruYqDwoHc0=",
      desc: "Private room in LES available march 1st. Must like dogs and cats. No couples. Close to trains and laundry mat",
      amenities: ['Pets welcome', 'Elevator', 'Wifi included', 'Balcony'],
      duraction: '12 month',
      rooms: 1,
      gender: 'Female',
      verified: true,
    },
    {
      id: "4",
      city: "Taraz",
      location: "Panfilov Street",
      category: "Appartement",
      price: 80000,
      img: "https://media.istockphoto.com/id/1289883686/fr/photo/appartement-spacieux-avec-mur-de-fen%C3%AAtre.jpg?s=612x612&w=0&k=20&c=k9Dg_10QHtyZQ4f__8pNPKgKb4DIwuTLdruYqDwoHc0=",
      desc: "Private room in LES available march 1st. Must like dogs and cats. No couples. Close to trains and laundry mat",
      amenities: ['Pets welcome', 'Elevator', 'Wifi', 'Free parking'],
      duraction: 'Fixed',
      rooms: 1,
      gender: 'Male',
      verified: true,
    },
    {
      id: "5",
      city: "Shymkent",
      location: "Panfilov Street",
      category: "Room",
      price: 50000,
      img: "https://media.istockphoto.com/id/1289883686/fr/photo/appartement-spacieux-avec-mur-de-fen%C3%AAtre.jpg?s=612x612&w=0&k=20&c=k9Dg_10QHtyZQ4f__8pNPKgKb4DIwuTLdruYqDwoHc0=",
      desc: "Private room in LES available march 1st. Must like dogs and cats. No couples. Close to trains and laundry mat",
      amenities: ['Elevator', 'Wifi', 'Air Conditioning'],
      duraction: 'Flexible',
      rooms: 2,
      gender: 'Male',
      verified: false,
    },
    {
      id: "6",
      city: "Shymkent",
      location: "Panfilov Street",
      category: "Appartement",
      price: 80000,
      img: "https://media.istockphoto.com/id/1289883686/fr/photo/appartement-spacieux-avec-mur-de-fen%C3%AAtre.jpg?s=612x612&w=0&k=20&c=k9Dg_10QHtyZQ4f__8pNPKgKb4DIwuTLdruYqDwoHc0=",
      desc: "Private room in LES available march 1st. Must like dogs and cats. No couples. Close to trains and laundry mat",
      amenities: ['Elevator', 'Wifi'],
      duraction: 'Fixed',
      rooms: 1,
      gender: 'Male',
      verified: true,
    },
    
  ];
   
  export default Data;